# version: '3'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     # ports:
#     #   - "5550:5550"

version: '3'

services:
  # web:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
