/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    NamadaLogoSvg: typeof import('./../src/components/icon/NamadaLogoSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackingSvg: typeof import('./../src/components/icon/StackingSvg.vue')['default']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    ToggleButton: typeof import('./../src/components/core/ToggleButton.vue')['default']
    TransferSvg: typeof import('./../src/components/icon/TransferSvg.vue')['default']
    Wallet: typeof import('./../src/components/icon/wallet.vue')['default']
    WalletSvg: typeof import('./../src/components/icon/WalletSvg.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
