/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATag: typeof import('ant-design-vue/es')['Tag']
    CommonTableHeader: typeof import('./../src/components/common/CommonTableHeader.vue')['default']
    DynamicStatusTag: typeof import('./../src/components/common/DynamicStatusTag.vue')['default']
    DynamicTag: typeof import('./../src/components/common/DynamicTag.vue')['default']
    FieldTextCopyable: typeof import('./../src/components/common/FieldTextCopyable.vue')['default']
    MyValidatorsTable: typeof import('./../src/components/table/MyValidatorsTable.vue')['default']
    NamadaLogoSvg: typeof import('./../src/components/icon/NamadaLogoSvg.vue')['default']
    ProposalTable: typeof import('./../src/components/table/ProposalTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackingSvg: typeof import('./../src/components/icon/StackingSvg.vue')['default']
    ToggleButton: typeof import('./../src/components/core/ToggleButton.vue')['default']
    TransferSvg: typeof import('./../src/components/icon/TransferSvg.vue')['default']
    ValidatorsTable: typeof import('./../src/components/table/ValidatorsTable.vue')['default']
    ValidatorSvg: typeof import('./../src/components/icon/ValidatorSvg.vue')['default']
    WalletSvg: typeof import('./../src/components/icon/WalletSvg.vue')['default']
  }
}
